export const FETCH_ROUTES_REQUEST = 'FETCH_ROUTES_REQUEST';
export const FETCH_ROUTES_FAILURE = 'FETCH_ROUTES_FAILURE';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const SET_MIN_PRICE = 'SET_MIN_PRICE';
export const SET_MAX_PRICE = 'SET_MAX_PRICE';

export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const CLEAR_CURRENT_ROUTE = 'CLEAR_CURRENT_ROUTE';

export const SET_FROM_CITY = 'SET_FROM_CITY';
export const CLEAR_FROM_CITY = 'CLEAR_FROM_CITY';
export const SET_TO_CITY = 'SET_TO_CITY';
export const CLEAR_TO_CITY = 'CLEAR_TO_CITY';
export const SET_DATE_START = 'SET_DATE_START';
export const CLEAR_DATE_START = 'CLEAR_DATE_START';
export const SET_DATE_END = 'SET_DATE_END';
export const CLEAR_DATE_END = 'CLEAR_DATE_END';
export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const SET_TICKETS_QUANTITY = 'SET_TICKETS_QUANTITY';
export const CLEAR_TICKETS_QUANTITY = 'CLEAR_TICKETS_QUANTITY';
export const GET_AVAILABLE_SEATS = 'GET_AVAILABLE_SEATS';
export const SET_CAR_TYPE = 'SET_CAR_TYPE';
export const SET_CURRENT_COACH = 'SET_CURRENT_COACH';
export const CLEAR_CURRENT_COACH = 'CLEAR_CURRENT_COACH';
export const SET_SELECTED_SEATS = 'SET_SELECTED_SEATS';
export const CLEAR_SELECTED_SEATS = 'SELECTED_SEATS';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_PASSENGERS_AGE = 'SET_PASSENGERS_AGE';

export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_PASSENGERS_LIST = 'SET_PASSENGERS_LIST';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
